//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace project.ResourceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ResourceServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ResourceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOrUpdateRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrUpdateWorkPlaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrUpdateConferenceRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddOrUpdateBillboardOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteResourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeaseInOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeaseOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeaseDelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ResourceService() {
            this.Url = global::project.Properties.Settings.Default.project_ResourceService_ResourceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddOrUpdateRoomCompletedEventHandler AddOrUpdateRoomCompleted;
        
        /// <remarks/>
        public event AddOrUpdateWorkPlaceCompletedEventHandler AddOrUpdateWorkPlaceCompleted;
        
        /// <remarks/>
        public event AddOrUpdateConferenceRoomCompletedEventHandler AddOrUpdateConferenceRoomCompleted;
        
        /// <remarks/>
        public event AddOrUpdateBillboardCompletedEventHandler AddOrUpdateBillboardCompleted;
        
        /// <remarks/>
        public event DeleteResourceCompletedEventHandler DeleteResourceCompleted;
        
        /// <remarks/>
        public event LeaseInCompletedEventHandler LeaseInCompleted;
        
        /// <remarks/>
        public event LeaseOutCompletedEventHandler LeaseOutCompleted;
        
        /// <remarks/>
        public event LeaseDelCompletedEventHandler LeaseDelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrUpdateRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddOrUpdateRoom(string rmJsonObject) {
            object[] results = this.Invoke("AddOrUpdateRoom", new object[] {
                        rmJsonObject});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrUpdateRoomAsync(string rmJsonObject) {
            this.AddOrUpdateRoomAsync(rmJsonObject, null);
        }
        
        /// <remarks/>
        public void AddOrUpdateRoomAsync(string rmJsonObject, object userState) {
            if ((this.AddOrUpdateRoomOperationCompleted == null)) {
                this.AddOrUpdateRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateRoomOperationCompleted);
            }
            this.InvokeAsync("AddOrUpdateRoom", new object[] {
                        rmJsonObject}, this.AddOrUpdateRoomOperationCompleted, userState);
        }
        
        private void OnAddOrUpdateRoomOperationCompleted(object arg) {
            if ((this.AddOrUpdateRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrUpdateRoomCompleted(this, new AddOrUpdateRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrUpdateWorkPlace", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddOrUpdateWorkPlace(string wpJsonObject) {
            object[] results = this.Invoke("AddOrUpdateWorkPlace", new object[] {
                        wpJsonObject});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrUpdateWorkPlaceAsync(string wpJsonObject) {
            this.AddOrUpdateWorkPlaceAsync(wpJsonObject, null);
        }
        
        /// <remarks/>
        public void AddOrUpdateWorkPlaceAsync(string wpJsonObject, object userState) {
            if ((this.AddOrUpdateWorkPlaceOperationCompleted == null)) {
                this.AddOrUpdateWorkPlaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateWorkPlaceOperationCompleted);
            }
            this.InvokeAsync("AddOrUpdateWorkPlace", new object[] {
                        wpJsonObject}, this.AddOrUpdateWorkPlaceOperationCompleted, userState);
        }
        
        private void OnAddOrUpdateWorkPlaceOperationCompleted(object arg) {
            if ((this.AddOrUpdateWorkPlaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrUpdateWorkPlaceCompleted(this, new AddOrUpdateWorkPlaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrUpdateConferenceRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddOrUpdateConferenceRoom(string crJsonObject) {
            object[] results = this.Invoke("AddOrUpdateConferenceRoom", new object[] {
                        crJsonObject});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrUpdateConferenceRoomAsync(string crJsonObject) {
            this.AddOrUpdateConferenceRoomAsync(crJsonObject, null);
        }
        
        /// <remarks/>
        public void AddOrUpdateConferenceRoomAsync(string crJsonObject, object userState) {
            if ((this.AddOrUpdateConferenceRoomOperationCompleted == null)) {
                this.AddOrUpdateConferenceRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateConferenceRoomOperationCompleted);
            }
            this.InvokeAsync("AddOrUpdateConferenceRoom", new object[] {
                        crJsonObject}, this.AddOrUpdateConferenceRoomOperationCompleted, userState);
        }
        
        private void OnAddOrUpdateConferenceRoomOperationCompleted(object arg) {
            if ((this.AddOrUpdateConferenceRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrUpdateConferenceRoomCompleted(this, new AddOrUpdateConferenceRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddOrUpdateBillboard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddOrUpdateBillboard(string bbJsonObject) {
            object[] results = this.Invoke("AddOrUpdateBillboard", new object[] {
                        bbJsonObject});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddOrUpdateBillboardAsync(string bbJsonObject) {
            this.AddOrUpdateBillboardAsync(bbJsonObject, null);
        }
        
        /// <remarks/>
        public void AddOrUpdateBillboardAsync(string bbJsonObject, object userState) {
            if ((this.AddOrUpdateBillboardOperationCompleted == null)) {
                this.AddOrUpdateBillboardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOrUpdateBillboardOperationCompleted);
            }
            this.InvokeAsync("AddOrUpdateBillboard", new object[] {
                        bbJsonObject}, this.AddOrUpdateBillboardOperationCompleted, userState);
        }
        
        private void OnAddOrUpdateBillboardOperationCompleted(object arg) {
            if ((this.AddOrUpdateBillboardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddOrUpdateBillboardCompleted(this, new AddOrUpdateBillboardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteResource", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteResource(string resourceId) {
            object[] results = this.Invoke("DeleteResource", new object[] {
                        resourceId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteResourceAsync(string resourceId) {
            this.DeleteResourceAsync(resourceId, null);
        }
        
        /// <remarks/>
        public void DeleteResourceAsync(string resourceId, object userState) {
            if ((this.DeleteResourceOperationCompleted == null)) {
                this.DeleteResourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteResourceOperationCompleted);
            }
            this.InvokeAsync("DeleteResource", new object[] {
                        resourceId}, this.DeleteResourceOperationCompleted, userState);
        }
        
        private void OnDeleteResourceOperationCompleted(object arg) {
            if ((this.DeleteResourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteResourceCompleted(this, new DeleteResourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeaseIn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LeaseIn(string jsonList) {
            object[] results = this.Invoke("LeaseIn", new object[] {
                        jsonList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LeaseInAsync(string jsonList) {
            this.LeaseInAsync(jsonList, null);
        }
        
        /// <remarks/>
        public void LeaseInAsync(string jsonList, object userState) {
            if ((this.LeaseInOperationCompleted == null)) {
                this.LeaseInOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeaseInOperationCompleted);
            }
            this.InvokeAsync("LeaseIn", new object[] {
                        jsonList}, this.LeaseInOperationCompleted, userState);
        }
        
        private void OnLeaseInOperationCompleted(object arg) {
            if ((this.LeaseInCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeaseInCompleted(this, new LeaseInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeaseOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LeaseOut(string jsonList) {
            object[] results = this.Invoke("LeaseOut", new object[] {
                        jsonList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LeaseOutAsync(string jsonList) {
            this.LeaseOutAsync(jsonList, null);
        }
        
        /// <remarks/>
        public void LeaseOutAsync(string jsonList, object userState) {
            if ((this.LeaseOutOperationCompleted == null)) {
                this.LeaseOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeaseOutOperationCompleted);
            }
            this.InvokeAsync("LeaseOut", new object[] {
                        jsonList}, this.LeaseOutOperationCompleted, userState);
        }
        
        private void OnLeaseOutOperationCompleted(object arg) {
            if ((this.LeaseOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeaseOutCompleted(this, new LeaseOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeaseDel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LeaseDel(string jsonList) {
            object[] results = this.Invoke("LeaseDel", new object[] {
                        jsonList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LeaseDelAsync(string jsonList) {
            this.LeaseDelAsync(jsonList, null);
        }
        
        /// <remarks/>
        public void LeaseDelAsync(string jsonList, object userState) {
            if ((this.LeaseDelOperationCompleted == null)) {
                this.LeaseDelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeaseDelOperationCompleted);
            }
            this.InvokeAsync("LeaseDel", new object[] {
                        jsonList}, this.LeaseDelOperationCompleted, userState);
        }
        
        private void OnLeaseDelOperationCompleted(object arg) {
            if ((this.LeaseDelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeaseDelCompleted(this, new LeaseDelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddOrUpdateRoomCompletedEventHandler(object sender, AddOrUpdateRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrUpdateRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrUpdateRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddOrUpdateWorkPlaceCompletedEventHandler(object sender, AddOrUpdateWorkPlaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrUpdateWorkPlaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrUpdateWorkPlaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddOrUpdateConferenceRoomCompletedEventHandler(object sender, AddOrUpdateConferenceRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrUpdateConferenceRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrUpdateConferenceRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddOrUpdateBillboardCompletedEventHandler(object sender, AddOrUpdateBillboardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddOrUpdateBillboardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddOrUpdateBillboardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteResourceCompletedEventHandler(object sender, DeleteResourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteResourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteResourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LeaseInCompletedEventHandler(object sender, LeaseInCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeaseInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeaseInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LeaseOutCompletedEventHandler(object sender, LeaseOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeaseOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeaseOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LeaseDelCompletedEventHandler(object sender, LeaseDelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeaseDelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeaseDelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591